### ISSUE TITLE
*Request

### ISSUE THREAD

**Issue by alexandermburke** [iLexiconn/LLibraryLegacy#18]
Can you guys make it, to where you can completely re-arrange the main menu gui (I do not know how to Override MC GUIs only make them.)?
Thanks In advance - Magik

**Comment by alexandermburke** [comment]
Wait nvm i might have found out how to do that :P

**Comment by FiskFille** [comment]
It is possible, although not recommended, as it might cause incompatibilities with other LLib mods trying to add elements to the main menu.
