### ISSUE TITLE
Crashed when i tried to add LLibrary to my pack!

### ISSUE THREAD

**Issue by Beanius** [iLexiconn/LLibraryLegacy#23]
http://pastebin.com/hBxHMuEE
Seems like there's a problem between LLibrary and Smart render / Smart moving :O!!
or am i derping? :D If so my baaaaaaad <3
I really wanna use JurassiCraft, and LLibrary x_x as well with the smart moving, cause it's just epic to climb walls hahaha!

**Comment by iLexiconn** [comment]
LLibrary and Smart Moving both try to override the player renderer, and that causes that crash. We can't fix it, sorry.

**Comment by Beanius** [comment]
Oh maaaan :O!! that's a bummer. I guess they won't ever be compatible then? Or could i send a message to Divisor, the maker of smart moving? :D

**Comment by iLexiconn** [comment]
You can try that :)

**Comment by Beanius** [comment]
i'm on it then!! :D Thanks alot iLexiconn!!!
