### ISSUE TITLE
Crash with EiraIRC after adding LLibrary to existing pack

### ISSUE THREAD

**Issue by Haggle1996** [iLexiconn/LLibraryLegacy#26]
https://gist.github.com/Haggle1996/0d33a960241f13aad705

Receiving the above error after adding LLibrary to an existing pack (http://bit.ly/1CLRfNc). It looks like a conflict with EiraIRC. I've tried several different versions of EiraIRC, but none work. Cross-posting to both issue trackers.

blay09/EiraIRC#281

**Comment by iLexiconn** [comment]
Fixed in https://github.com/blay09/EiraIRC/commit/74add062d3d60427a5555b9c8fd468fcf296c824
