### ISSUE TITLE
Sudden Crash on Startup?

### ISSUE THREAD

**Issue by Ankokou** [iLexiconn/LLibraryLegacy#27]
While I'm not very good at interpreting crashlogs, as far as I can tell the crash is an issue with LLibrary.
The modpack was working fine for several days, until today, when I'm suddenly getting this crash on launch. Any suggestions, ideas, or possibly fixes beyond removing the mod (and those dependent on it?)

http://pastebin.com/Bdj1bBr5

**Comment by iLexiconn** [comment]
Try to remove JurassiCraft

**Comment by Ankokou** [comment]
There you go, no JurassiCraft.
http://pastebin.com/5qQjhYHd

However that is from yesterday, in attempting to pinpoint the cause. Today, without me making any changes, it works again. 
I dunno why.

Anyway, I suppose it's up to you if you want to investigate the issue further. I certainly won't be offended if you close this.

**Comment by iLexiconn** [comment]
Did you check your internet? LLibrary crashes when you don't have an internet connection, but this is fixed in 0.2.1.
