### ISSUE TITLE
Incompatibility with Journeymap RC4

### ISSUE THREAD

**Issue by drakray** [iLexiconn/LLibraryLegacy#31]
http://pastebin.com/0RAu0Nm1
Got this crash when trying to Auto-Map All

**Comment by drakray** [comment]
Using 0.2.0

**Comment by iLexiconn** [comment]
Did you try using 0.3.0?

**Comment by drakray** [comment]
can't use 0.3.0, Jurassicraft not compatible

**Comment by iLexiconn** [comment]
Try uninstalling Jurassicraft

**Comment by iLexiconn** [comment]
Can I close this?
