### ISSUE TITLE
Crash with JourneyMap 5.10

### ISSUE THREAD

**Issue by Haggle1996** [iLexiconn/LLibraryLegacy#33]
http://pastebin.com/NpNyKc9r

With the latest versions of LLibrary and JourneyMap, receive the previous CTD when doing an Automap-All in JourneyMap. This happens regardless of having JurassiCraft installed (here's a crashlog without JC: http://pastebin.com/sPWsQ24r -- it's identical).

**Comment by iLexiconn** [comment]
Can you try using the latest version of llibrary?

**Comment by Haggle1996** [comment]
Sorry, forgot to report that this was no longer happening with the latest LLibrary and JourneyMap. Thanks for closing/fixing

**Comment by iLexiconn** [comment]
Great to hear that :)

**Comment by Haggle1996** [comment]
This issue has reappeared with LLibrary 0.6 

http://pastebin.com/3xtCjdXC

I should probably stop updating this mod. :P

**Comment by iLexiconn** [comment]
Did you also try 0.5.5?

**Comment by Haggle1996** [comment]
Yes, no crashes on 0.5.5.
