### ISSUE TITLE
Server side crash with LLibrary 0.4.0 for 1.7.10

### ISSUE THREAD

**Issue by hvdklauw** [iLexiconn/LLibraryLegacy#35]
hello,

I think LLibrary is doing something server side (or both sides) it should only do client side:
http://pastebin.com/De1xXqR1

LLibrary seems to be the only thing there that's not java, minecraft or forge related, before on 0.3.4 everything worked fine, but with llibrary updated we get this error.

**Comment by iLexiconn** [comment]
Thanks for the report, fixed in 0.4.1 (http://minecraft.curseforge.com/projects/llibrary/files/2261561)
