### ISSUE TITLE
net.ilexiconn.llibrary.common.entity.EntityMountableBlock cannot be cast to net.minecraft.entity.EntityLivingBase

### ISSUE THREAD

**Issue by ThomasAunvik** [iLexiconn/LLibraryLegacy#36]
Crashes everytime when i join a server:

Custom modpack server: 
http://www.technicpack.net/modpack/paradise-reloaded-pack.725661

Crash report.
http://pastebin.com/k2gTNcbu

**Comment by iLexiconn** [comment]
Does this still happen in LLibrary 0.4.3?

**Comment by ThomasAunvik** [comment]
I dont know, they downgraded the modpack to LLibary 0.3.4 and it has been doing fine.

**Comment by iLexiconn** [comment]
Well, I didn't change anything in the block code since 0.2.0, so I think it should be fine then. :)
