### ISSUE TITLE
When entering into the world - a black screen. And crash with exit from singleplayer

### ISSUE THREAD

**Issue by Tsyklop** [iLexiconn/LLibraryLegacy#46]
https://youtu.be/FIvBliSDxgQ look this.

Mod List: http://pastebin.com/8YxWEr4k

**Comment by iLexiconn** [comment]
Does this still happen when you uninstall JourneyMap?

**Comment by Tsyklop** [comment]
JourneyMap don`t install. Install VoxelMap(liteLoader)

**Comment by iLexiconn** [comment]
I'm pretty sure you listed it as installed, though. If you're sure you don't have it installed, try uninstalling SquidScript.

**Comment by Tsyklop** [comment]
@iLexiconn I removed - crash occur. the problem with the black screen is present.

error: http://pastebin.com/UTiQZkf6

**Comment by iLexiconn** [comment]
What happens when you remove the weather mod?

**Comment by Tsyklop** [comment]
@iLexiconn Hmmm. I delete weather mod and all OK. But i need this mod

**Comment by iLexiconn** [comment]
That mod isn't open-source, so I can't check out what's causing the error, sorry.

**Comment by pau101** [comment]
@iLexiconn The weather mod is open source https://github.com/Corosauce/weather2

**Comment by iLexiconn** [comment]
Oh,  I couldn't find it on his site.
