### ISSUE TITLE
Crashes when world loads.

### ISSUE THREAD

**Issue by ghost** [iLexiconn/LLibraryLegacy#49]
I keep getting this error report.
http://pastebin.com/jcZ1xbC7

**Comment by iLexiconn** [comment]
Can you tell me exactly what happend before it crashed, please? I can't reproduce this.

**Comment by ghost** [comment]
Well, the game starts up fine then when I go to load the world it pops up the with screen saying "Loading World" and it goes to a black screen after 30 seconds as if the world is ready to load then crashes.

**Comment by iLexiconn** [comment]
Does this also happen in new worlds?

**Comment by ghost** [comment]
It happens with every world that I try to load.

**Comment by DanielleHuisman** [comment]
I can't seem to reproduce it in the development environment, haven't tried obfuscated environment though

**Comment by DanielleHuisman** [comment]
Could you try it with the latest Forge and without any other mods?

**Comment by ghost** [comment]
That seems to make the world not load anymore. If you want, I can give you a compressed file with every mod in it.

**Comment by DanielleHuisman** [comment]
Please update to the latest Forge and remove all other mods but LLibrary.
If this error re-occurs with only LLibrary, post the error log or full FML log.

**Comment by ghost** [comment]
It loads with latest version and just llibrary.

**Comment by DanielleHuisman** [comment]
Ok, then try adding mods one by one until it does crash

**Comment by iLexiconn** [comment]
Can you try loading the world with all the mods, except AM2, OpenModsCore, DragonAPI and CodeChickenCore?

**Comment by ghost** [comment]
When I removed those, it instantly closed but didn't crash.

**Comment by iLexiconn** [comment]
You have to remove the mods dependeing on those mods too.

**Comment by ghost** [comment]
I do not think the world is going to load now.

**Comment by ghost** [comment]
It finally loaded but it crashed.
http://pastebin.com/NLE8i5zu

**Comment by iLexiconn** [comment]
Can you also remove appliedenergistics2?

**Comment by ghost** [comment]
Same crash.

**Comment by iLexiconn** [comment]
Please continue removing mods util it doesn't crash anymore, like @DanielHuisman said. Once the crash is fixed, please tell us what mod you removed last.

**Comment by ghost** [comment]
After 43 minutes of trial and error, I have concluded that it was Thaumic Horizons that was causing the crash.

**Comment by DanielleHuisman** [comment]
I couldn't find the source code of Thaumic Horizons, but I did a quick decompile of the jar and I don't think there is anything we can do about it. 
A similar error will probably occur when you only have Thaumic Horizons (and Thaumcraft obviously) installed.
I'm closing this issue for now, but if you feel like investigating you can post any progress in this thread.
