### ISSUE TITLE
Change ASM helper's config handling

### ISSUE THREAD

**Issue by DanielleHuisman** [iLexiconn/LLibraryLegacy#58]
Currently the ASM helper usese the LLibrary config handlers and these get loaded during pre-init, but the ASM helper can be called earlier, so we also need to implement the CCL config handler.

**Comment by iLexiconn** [comment]
Just make sure not to any break older mods using llib

**Comment by DanielleHuisman** [comment]
Fixed in latest commit (c64edfd)
