### ISSUE TITLE
Crash with NEI

### ISSUE THREAD

**Issue by Darkhax** [iLexiconn/LLibraryLegacy#59]
When accessing one of the vanilla creative tabs, I received the following crash. The stack trace points to NEI and LLibrary methods. 

https://gist.github.com/darkhax/a77baea73cf88e9f40a8

**Comment by iLexiconn** [comment]
Pretty sure it isn't LLibrary. Our player model can't cause the crash, as it doesn't touch any item code.

**Comment by Darkhax** [comment]
This is probably something on NEI's side, however that crash is a legitimate one, I generated it myself while testing on the Better Than Minecon server :p

**Comment by iLexiconn** [comment]
Does it also happen without having LLibrary installed?

**Comment by Darkhax** [comment]
It's hard to reproduce, I am not sure how, it just randomly happens. I haven't had this issue with LLibrary not installed. Also, LLibrary is part of the stack trace.

**Comment by iLexiconn** [comment]
That's mainly because LLibrary replaces the player model to call it's own events. It doesn't overwrite any vanilla code.
