### ISSUE TITLE
No open GL Context issue

### ISSUE THREAD

**Issue by baradhili** [iLexiconn/LLibraryLegacy#63]
Hi All,
noticing this on a 1.8.8 system with forge - any ideas? Removing llibrary & Jurassicraft cleans up the problem, but doesn't make my 6yr old very happy ...

Cheers
Bret

http://pastebin.com/sSiQgwKf

**Comment by iLexiconn** [comment]
Can you tell me when the client crashes? For example; On startup, on world load or on random times.

**Comment by baradhili** [comment]
on world load, forge is happy with it and its only when you try and load a world that it spits..

**Comment by baradhili** [comment]
Here is the log..
http://pastebin.com/fPL6F4zS

**Comment by iLexiconn** [comment]
Does it also happen when you remove JurassiCraft, but keep LLibrary?

**Comment by baradhili** [comment]
trying that now...

**Comment by baradhili** [comment]
oh awesome, clearing out all mods, creating new plain world and just having llibrary - no issues, adding jurassicraft 2.0.0. pre 5 - no issues...

'its gunna be a long night...

**Comment by iLexiconn** [comment]
This probably means that one of JurassiCraft's entities is corrupted. The only way to fix it to load the world in without JurassiCraft, save it, and add JurassiCraft again.

**Comment by baradhili** [comment]
could be.. I reloaded each mod one by one and loaded the world and nothing crashed... 

So I guess you can close this bug...

**Comment by iLexiconn** [comment]
:+1:
