### ISSUE TITLE
1.8.9 - Client Startup Crash

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [iLexiconn/LLibraryLegacy#65]
I was reading something and I don't plan on removing mods but I will report the crash and you can do what you want with it.

Crash Log -> https://gist.github.com/DPxKnightxZero/04617533444a1fb0268b

Full Client Log -> https://gist.github.com/DPxKnightxZero/cb58712f166ccc248c6a

**Comment by iLexiconn** [comment]
LLibrary is not compatible with the shaders mod. This'll get fixed in the new update (0.8.0).
