### ISSUE TITLE
0.4.3 crashing due to version check failing

### ISSUE THREAD

**Issue by sunshinehunter** [iLexiconn/LLibraryLegacy#66]
Hello, LLibrary 0.4.3 (specifically, the whole Rexxit modpack) is crashing because the version check isn't working anymore, since file(s?) got removed. Here's the full crash: https://cdn.discordapp.com/attachments/139760181570437120/139767026179768320/crash-2016-01-21_10.21.56-client.txt

I don't have a full log on hand right now, but I got this specific part out of one

```
[11:53:33] [Server thread/ERROR] [llibrary/jurassicraft]: Failed connecting to 'http://ilexiconn.net/llibrary/data/llibrary_64.png'. (Server returned HTTP response code: 403 for URL: http://ilexiconn.net/llibrary/data/llibrary_64.png)
```

Updating it to 0.5.5 or 0.7.2 fixs it, but as the modpack dev is unavailable right now, it would be easier if you could restore the missing files. Thank you!

**Comment by iLexiconn** [comment]
Sorry, but I can't fix it. My site structure has changed a lot, and made the /llibrary/ directory unavailable.
