### ISSUE TITLE
RTG incompatible with LLibrary's structure API?

### ISSUE THREAD

**Issue by whichonespink44** [iLexiconn/LLibraryLegacy#67]
Hi iLexiconn -

I posted a crash report over at the Mowzie's Mobs thread a few months ago related to the Ferrous Wroughtnaut's chamber generation, but I was quite certain that it was caused by the unorthodox way that RWG was generating biomes at the time, so I never followed up.

Since then, however, I started working on a fork of RWG called Realistic Terrain Generation ([RTG](https://github.com/Team-RTG/Realistic-Terrain-Generation)), and recently we changed the way RTG generates biomes so that it's more aligned with the way vanilla Minecraft/Forge does things (using the GenLayer system), so I thought I'd see if the crash was still happening... and unfortunately, it is:

Crash report: https://gist.github.com/whichonespink44/129464d524711213d14d
Configs: https://goo.gl/0T3fJS

When I [posted this](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2361125-mowzies-mobs-fantastical-mobs-for-your-mc-world?comment=3341) on Mowzie's thread, he replied with the following:

> Hm... The crash is actually traced back to an incompatibility with LLibrary's structure API. I couldn't tell you the specifics, but a fix would require an edit of LLibrary, not Mowzie's Mobs. Sorry.

Is there anything that RTG can do differently that would resolve this incompatibility? If not, is there anything that can be done at all?

If you need any additional information from me, please let me know.

Cheers,
Pink

**Comment by iLexiconn** [comment]
See https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/442
